name=HijelHID_BLEMouse
version=0.1.0
author=Hijel
maintainer=Hijel hijel.hub@gmail.com
sentence=Bluetooth Low Energy (BLE) HID Mouse library for ESP32 using NimBLE-Arduino 2.3.8+
paragraph=Supports creation of 3, 5, or 7(5 + Horizontal Scroll) button mouse device. Power saving, macro movement helpers, and deep sleep ready. ISR-safe base layer.
category=Communication
url=https://github.com/HijelHub/HijelHID_BLEMouse
architectures=esp32
depends=NimBLE-Arduino
